controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

indice:
    path: /
    controller: App\Controller\IndexController::index
pod:
    path: /pod
    controller: App\Controller\Controlador1Controller::index
service:
    path: /service
    controller: App\Controller\Controlador2Controller::index
deploymente:
    path: /deployment
    controller: App\Controller\Controlador3Controller::index
replicaset:
    path: /replicaset
    controller: App\Controller\Controlador4Controller::index
nginx:
    path: /nginx
    controller: App\Controller\Controlador5Controller::index
reinicio:
    path: /reiniciar
    controller: App\Controller\ReiniciarController::index
parar:
    path: /parar
    controller: App\Controller\PararController::index
cerrar:
    path: /cerrar
    controller: App\Controller\CerrarController::index

    

    